name: Python App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install dependencies (mirrors your 'install' target)
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Lint the code (mirrors your 'lint' target)
      - name: Lint with pylint
        run: |
          pylint --disable=R,C hello.py

      # Format the code (mirrors your 'format' target)
      - name: Format with black
        run: |
          black --check *.py

      # Run tests (mirrors your 'test' target)
      - name: Run tests with pytest
        run: |
          python -m pytest -vv test_hello.py
